### PR TITLE
CONTROLLERS: Lab Artifacts Post

### PR DESCRIPTION
**Pull request by geetika-jain**

### CODE REVIEW

**Review by AndrewMcClelland — COMMENTED** [review]
Pending completion of #102

**Review by AndrewMcClelland — DISMISSED** [review]
Pending completion of #102

**Comment by geetika-jain** [comment]
@AndrewMcClelland There are acceptance tests in this PR that you 'requested changes' for... was that intentional? Can we move them to a new PR?

**Comment by AndrewMcClelland** [comment]
> @AndrewMcClelland There are acceptance tests in this PR that you 'requested changes' for... was that intentional? Can we move them to a new PR?

I was trying to just leave a comment to block the PR until #102 completed.... I clearly don't understand how GitHub works :grinning: Dismissed it!

**Review by hassanhabib — APPROVED** [review]

**Pull request merged**
